version: '3.8'

services:
  driver-app:
    container_name: "driver-app"
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgresdb@localhost:5432/driver_app?schema=public
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=${NODE_ENV}
    networks:
      - app-network
    restart: always

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: